from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any
from ..models import AccountState, InstrumentRules
class ExchangeError(RuntimeError):
    def __init__(self,code:str,msg:str='',*,retryable=False,reconcile_first=False,lock_required=False): super().__init__(f'{code}:{msg}'); self.code=code; self.retryable=retryable; self.reconcile_first=reconcile_first; self.lock_required=lock_required
class ExecutionExchangeAdapter(ABC):
    @abstractmethod
    def get_account_state(self)->AccountState: ...
    @abstractmethod
    def get_instrument_rules(self,symbol:str)->InstrumentRules: ...
    @abstractmethod
    def get_fee_schedule(self,symbol:str)->dict[str,Any]: ...
    @abstractmethod
    def get_open_orders(self,symbol:str|None=None)->list[dict[str,Any]]: ...
    @abstractmethod
    def get_positions(self,symbol:str|None=None)->list[dict[str,Any]]: ...
    @abstractmethod
    def place_order(self,order:dict[str,Any])->dict[str,Any]: ...
    @abstractmethod
    def cancel_order(self,symbol:str,client_id:str)->dict[str,Any]: ...
    @abstractmethod
    def get_executions(self,symbol:str|None=None)->list[dict[str,Any]]: ...
    @abstractmethod
    def set_protection(self,position:dict[str,Any],stop:str,targets:list[dict[str,Any]])->dict[str,Any]: ...
